/*
SQLyog Community v13.2.0 (64 bit)
MySQL - 8.1.0 : Database - db_java1234_rag
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`db_java1234_rag` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `db_java1234_rag`;

/*Table structure for table `t_chat_message` */

DROP TABLE IF EXISTS `t_chat_message`;

CREATE TABLE `t_chat_message` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `session_id` bigint NOT NULL COMMENT '会话ID',
  `role` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'USER / ASSISTANT',
  `content` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息内容',
  `refs` json DEFAULT NULL COMMENT '引用文档JSON',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_session` (`session_id`)
) ENGINE=InnoDB AUTO_INCREMENT=95 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='聊天消息';

/*Data for the table `t_chat_message` */

insert  into `t_chat_message`(`id`,`session_id`,`role`,`content`,`refs`,`create_time`) values 
(3,2,'USER','项目开发 统一响应结构 如何设计？',NULL,'2026-05-11 15:11:16'),
(4,2,'ASSISTANT','# 项目开发中统一响应结构的设计\n\n根据知识库上下文，项目开发中统一响应结构的设计如下：\n\n## 统一JSON响应结构\n所有接口必须返回以下标准化JSON格式：\n```json\n{\n  \"code\": 200,\n  \"message\": \"操作成功\",\n  \"data\": {}\n}\n```\n\n### 字段说明\n| 字段 | 类型 | 说明 |\n|------|------|------|\n| `code` | 整数 | 操作状态码（例如：200表示成功，400表示参数错误） |\n| `message` | 字符串 | 操作结果描述（例如：\"操作成功\"） |\n| `data` | 对象 | 业务数据容器（可为空） |\n\n## 设计要点\n- **状态码规范**：`code` 值需符合HTTP状态码标准（如200、400、500等），确保前后端可快速识别操作结果。\n- **可读性**：`message` 字段提供用户友好的操作描述，避免直接暴露业务细节。\n- **数据隔离**：`data` 字段用于承载业务数据，与状态码和消息解耦，便于错误处理和数据扩展。\n- **强制统一**：所有接口必须严格遵循此结构，避免响应格式不一致导致的前端兼容问题。\n\n> 注：上下文未指定具体文档标题，但此设计规范直接来源于知识库提供的API设计上下文。\n\n依据的文档标题：Java1234 RAG 企业知识库（上下文内容）','[{\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 200,\\n  \\\"message\\\": \\\"操作成功\\\",\\n  \\\"data\\\": {}\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 200,\\n  \\\"message\\\": \\\"操作成功\\\",\\n  \\\"data\\\": {}\\n}\", \"categoryId\": null}]','2026-05-11 15:11:16'),
(5,3,'USER','项目开发 统一响应结构 如何设计？',NULL,'2026-05-11 15:16:24'),
(6,3,'ASSISTANT','# 项目开发统一响应结构设计\n\n根据知识库中的信息，项目开发中统一响应结构的设计应严格遵循以下规范：\n\n- **统一JSON响应结构**：所有接口返回的JSON格式必须为：\n  ```json\n  {\n    \"code\": 200,\n    \"message\": \"操作成功\",\n    \"data\": {}\n  }\n  ```\n\n- **关键字段说明**：\n  - `code`：整数状态码（例如：200表示成功，400表示参数错误）\n  - `message`：字符串，描述操作结果的简要信息\n  - `data`：对象，用于存储业务数据（可为空）\n\n该设计确保了API接口的标准化，便于前端调用、后端维护和错误统一处理，同时符合企业级API开发的最佳实践。\n\n依据的文档标题：Java1234 RAG 企业知识库','[{\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 200,\\n  \\\"message\\\": \\\"操作成功\\\",\\n  \\\"data\\\": {}\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 200,\\n  \\\"message\\\": \\\"操作成功\\\",\\n  \\\"data\\\": {}\\n}\", \"categoryId\": null}]','2026-05-11 15:16:24'),
(7,4,'USER','项目 统一响应结构 规范是啥？',NULL,'2026-05-11 15:16:24'),
(8,4,'ASSISTANT','# 项目统一响应结构规范\n\n根据检索到的上下文，**项目统一响应结构规范**是公司内部RESTful API设计标准中关于接口响应结构的核心要求，具体规定如下：\n\n- **所有接口必须返回统一的JSON结构**  \n  （规范明确要求：接口响应需遵循一致的JSON格式，以确保接口的一致性、可读性和可维护性）\n\n### 关键说明\n- 该规范是公司内部RESTful API设计标准的一部分，覆盖所有后端开发人员在API设计和开发时的实践。\n- 上下文中未提供JSON结构的具体字段、格式或示例（如`code`、`message`等细节），但规范强调**响应必须是统一的JSON格式**。\n- 其他相关规范要求（如协议、URL设计）已包含在上下文中，但本问题聚焦于响应结构部分。\n\n> ⚠️ **注意**：知识库中未详细描述JSON结构的完整字段定义（例如具体字段名、数据类型），因此无法提供更细粒度的响应结构示例。\n\n依据的文档标题：`统一公司内部RESTful API设计标准`','[{\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}]','2026-05-11 15:16:24'),
(11,6,'USER','项目 统一响应结构 规范是啥？',NULL,'2026-05-11 15:22:33'),
(12,6,'ASSISTANT','## 项目统一响应结构规范\n\n根据检索到的上下文，**知识库中未找到相关信息**。原因如下：\n\n1.  **上下文内容不足**：  \n   检索到的上下文仅提到“所有接口返回统一的JSON结构”，但**未提供该JSON结构的具体字段、格式、示例或规范细节**（如响应码、数据字段定义、错误处理等）。用户询问的“项目统一响应结构规范”需要明确的响应结构定义，而上下文在此部分被截断且无实质内容。\n\n2.  **上下文聚焦于API设计而非响应结构**：  \n   上下文主要描述了API设计规范（如使用HTTPS、API版本号位置、资源命名规则等），但**未深入说明响应结构的规范要求**。例如，上下文未提及JSON结构中必须包含的字段（如`code`、`message`、`data`等）、数据类型或错误场景处理。\n\n因此，无法基于当前知识库内容回答“项目统一响应结构规范是啥”的问题。\n\n依据的文档标题：公司内部RESTful API设计规范（上下文片段）','[{\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}]','2026-05-11 15:22:33'),
(13,7,'USER','项目 统一响应结构 规范是啥？',NULL,'2026-05-11 15:26:15'),
(14,7,'ASSISTANT','# 统一响应结构规范说明\n\n根据检索到的知识片段，公司内部RESTful API的统一响应结构规范如下：\n\n- **所有接口返回统一的JSON结构**（知识库中未提供该JSON结构的具体字段、格式或示例）\n\n## 重要说明\n1. 知识库中**未详细说明**该JSON结构的具体内容（如字段名称、数据类型、错误处理等）。片段仅提及\"所有接口返回统一的JSON结构\"，但未给出具体规范细节。\n2. 知识库中**未找到与\"项目\"相关的具体响应结构规范信息**。所有片段均未提及\"项目\"在API响应结构中的特殊定义或要求。\n\n## 依据的文档片段\n- 片段 3: \"所有接口返回统一的JSON结构：\"\n- 片段 6: \"所有接口返回统一的JSON结构：\"\n\n> **注**：知识库中未找到与用户问题中\"项目\"相关的具体规范信息，也未提供JSON结构的完整细节。','[{\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}]','2026-05-11 15:26:15'),
(15,8,'USER','公司密码要求是啥？',NULL,'2026-05-11 15:28:31'),
(16,8,'ASSISTANT','## 知识库响应\n\n知识库中未找到相关信息。\n\n**原因**：系统检索未命中足够相关的片段，无法提供公司密码要求的具体内容。作为智能助手，我严格遵循检索结果，不编造任何信息。\n\n依据的文档：未检索到相关文档','[]','2026-05-11 15:28:31'),
(17,9,'USER','企业OA系统账号密码要求有哪些？\n ',NULL,'2026-05-11 15:30:28'),
(18,9,'ASSISTANT','# 知识库响应\n\n知识库中未找到相关信息。\n\n依据的文档标题：无','[]','2026-05-11 15:30:28'),
(19,10,'USER','新员工入职手续有哪些？\n ',NULL,'2026-05-11 15:32:45'),
(20,10,'ASSISTANT','# 知识库响应\n\n根据系统检索结果，知识库中未命中足够相关的片段，因此无法提供新员工入职手续的信息。知识库中未找到相关信息。\n\n依据的文档：无','[]','2026-05-11 15:32:45'),
(21,11,'USER','新员工入职手续有哪些？\n ',NULL,'2026-05-11 15:34:14'),
(22,11,'ASSISTANT','知识库中未找到相关信息\n\n根据检索到的全部片段，所有内容均聚焦于**员工请假管理流程**（片段2-5）和**任务系统功能**（片段6），**未包含任何关于新员工入职手续的描述**。片段3虽提及\"试用期员工\"，但仅说明该办法的适用范围，未涉及入职手续的具体内容。\n\n> 依据的文档标题：  \n> - 片段 1（无标题）  \n> - 片段 2（无标题）  \n> - 片段 3（无标题）  \n> - 片段 4（无标题）  \n> - 片段 5（无标题）  \n> - 片段 6（无标题）','[{\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"为规范公司员工请假管理流程，保障员工合法休假权益，确保公司各项工作正常运转，特制定本办法。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"本办法适用于公司全体在职员工，包括试用期员工。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"遇紧急情况无法提前申请的，可先电话向直属主管报备，事后在1个工作日内补办请假手续。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"查看和更新任务状态 接收任务变更通知 查看项目进度和统计数据 支持拍照上传附件\", \"categoryId\": null}]','2026-05-11 15:34:14'),
(23,12,'USER','python命名规范有哪些?\n ',NULL,'2026-05-11 15:38:47'),
(24,12,'ASSISTANT','# Python命名规范\n\n根据检索到的公司内部Python开发编码规范文档，Python命名规范具体包括以下内容：\n\n## 1. 模块和包命名\n- 模块名使用小写字母，多个单词之间用下划线连接（例如：`user_service.py`）\n- 包名使用小写字母，尽量不使用下划线（例如：`utils`、`models`）\n\n## 2. 类命名\n- 使用大驼峰命名法（PascalCase）（例如：`UserService`、`OrderManager`）\n- 异常类以 `Error` 或 `Exception` 结尾（例如：`InvalidTokenError`）\n\n## 3. 函数和方法命名\n- 使用小写字母和下划线（例如：`get_user_info`、`calculate_total_price`）\n- 私有方法以单下划线开头（例如：`_validate_input`）\n- 布尔类型的方法或变量建议使用 `is_`、`has_`、`can_` 前缀（例如：`is_valid`、`has_permission`）\n\n## 4. 变量命名\n- 使用小写字母和下划线（例如：`user_name`、`order_count`）\n- 常量使用全大写字母和下划线（例如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`）\n- 避免使用单字母变量名（循环变量 `i`、`j`、`k` 除外）\n\n## 5. 数据库相关命名\n- 数据库名以 `db_` 开头\n- 表名以 `t_` 开头，使用小写和下划线\n- 字段名使用小写和下划线\n\n> **说明**：以上规范均基于公司内部统一的《Python开发编码规范》文档，该规范主要参考PEP 8风格指南并结合公司实际开发需求制定。\n\n**依据的文档标题**：公司内部Python开发编码规范（检索到的6个片段均来自同一规范文档）','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}]','2026-05-11 15:38:47'),
(25,13,'USER','python命名规范有哪些?\n ',NULL,'2026-05-11 15:40:03'),
(26,13,'ASSISTANT','# 知识库响应\n\n知识库中未找到与“python命名规范有哪些?”相关的信息。  \n\n依据的文档标题：无','[]','2026-05-11 15:40:03'),
(27,14,'USER','python命名规范有哪些?',NULL,'2026-05-11 15:45:05'),
(28,14,'ASSISTANT','## 知识库中未找到相关信息\n\n根据系统检索结果，知识库未命中足够相关的片段以回答“python命名规范有哪些?”的问题。因此，无法提供Python命名规范的具体内容。\n\n**依据的文档标题**：无','[]','2026-05-11 15:45:05'),
(29,15,'USER','python命名规范有哪些?',NULL,'2026-05-11 15:49:15'),
(30,15,'ASSISTANT','# Python命名规范\n\n根据检索到的知识库，公司内部Python项目的命名规范如下：\n\n## 1. 模块和包命名\n- 模块名使用小写字母，多个单词之间用下划线连接，如：`user_service.py`\n- 包名使用小写字母，尽量不使用下划线，如：`utils`、`models`\n\n## 2. 类命名\n- 使用大驼峰命名法（PascalCase），如：`UserService`、`OrderManager`\n- 异常类以`Error`或`Exception`结尾，如：`InvalidTokenError`\n\n## 3. 函数和方法命名\n- 使用小写字母和下划线，如：`get_user_info`、`calculate_total_price`\n- 私有方法以单下划线开头，如：`_validate_input`\n- 布尔类型的方法或变量建议使用`is_`、`has_`、`can_`前缀\n\n## 4. 变量命名\n- 使用小写字母和下划线，如：`user_name`、`order_count`\n- 常量使用全大写字母和下划线，如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`\n- 避免使用单字母变量名（循环变量`i`、`j`、`k`除外）\n\n## 5. 数据库相关命名\n- 数据库名以`db_`开头\n- 表名以`t_`开头，使用小写和下划线\n- 字段名使用小写和下划线\n\n依据的文档标题：Python开发编码规范（检索到的片段1、3、4、6）','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}]','2026-05-11 15:49:15'),
(31,16,'USER','python命名规范有哪些?',NULL,'2026-05-11 15:56:17'),
(32,16,'ASSISTANT','## 知识库检索结果\n\n知识库中未找到与“python命名规范有哪些?”相关的信息。  \n\n依据的文档标题：无','[]','2026-05-11 15:56:17'),
(33,18,'USER','Python 命名规范有哪些？',NULL,'2026-05-11 16:01:03'),
(34,18,'ASSISTANT','## 知识库响应\n\n知识库中未找到与“Python 命名规范”相关的信息片段。根据系统说明，检索未命中足够相关的片段，因此无法提供任何相关信息。我不会编造或推测任何内容。\n\n依据的文档标题：无','[]','2026-05-11 16:01:03'),
(35,19,'USER','python命名规范有哪些？',NULL,'2026-05-11 16:16:18'),
(36,19,'ASSISTANT','## 答案\n\n知识库中未找到相关信息。\n\n依据：知识库检索未命中足够相关的片段。','[]','2026-05-11 16:16:18'),
(37,20,'USER','python命名规范有哪些？',NULL,'2026-05-11 16:24:07'),
(38,20,'ASSISTANT','# 知识库回答\n\n知识库中未找到相关信息。\n\n依据的文档标题：无','[]','2026-05-11 16:24:07'),
(39,25,'USER','python命名规范有哪些？',NULL,'2026-05-11 16:30:19'),
(40,25,'ASSISTANT','## 知识库响应\n\n知识库中未找到相关信息。\n\n依据的文档标题：无','[]','2026-05-11 16:30:19'),
(41,26,'USER','python命名规范有哪些？',NULL,'2026-05-11 16:48:36'),
(42,26,'ASSISTANT','# 回答\n\n知识库中未找到相关信息。\n\n**依据**：系统提示（知识库检索未命中足够相关的片段）','[]','2026-05-11 16:48:36'),
(43,27,'USER','python命名规范有哪些？',NULL,'2026-05-11 16:53:12'),
(44,27,'ASSISTANT','# Python命名规范\n\n根据企业知识库中检索到的上下文（所有相关片段均来自统一的**Python开发编码规范**文档），以下是企业内部Python命名规范的详细说明。这些规范基于PEP 8原则并结合企业实际实践制定，适用于模块、类、函数、变量等命名场景。\n\n## 模块和包命名\n- **模块名**：使用小写字母，多个单词之间用下划线连接（例如：`user_service.py`）。\n- **包名**：使用小写字母，尽量避免下划线（例如：`utils`、`models`）。\n\n## 类命名\n- **类名**：使用大驼峰命名法（PascalCase），首字母大写（例如：`UserService`、`OrderManager`）。\n- **异常类**：以 `Error` 或 `Exception` 结尾（例如：`InvalidTokenError`）。\n\n## 函数和方法命名\n- **函数/方法名**：使用小写字母和下划线（例如：`get_user_info`、`calculate_total_price`）。\n- **私有方法**：以单下划线开头（例如：`_validate_input`）。\n- **布尔类型标识**：建议使用 `is_`、`has_`、`can_` 前缀（例如：`is_active`、`has_permission`）。\n\n## 变量命名\n- **变量名**：使用小写字母和下划线（例如：`user_name`、`order_count`）。\n- **常量**：使用全大写字母和下划线（例如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`）。\n- **单字母变量**：仅允许循环变量（例如：`i`、`j`、`k`），其他场景避免使用单字母变量。\n\n## 数据库相关命名\n- **数据库名**：以 `db_` 开头（例如：`db_connection`）。\n- **表名**：以 `t_` 开头，使用小写和下划线（例如：`t_user`）。\n- **字段名**：使用小写和下划线（例如：`user_name`、`created_at`）。\n\n> **说明**：以上规范均来自企业内部统一的Python开发编码规范文档（版本一致），确保代码可读性、可维护性及团队协作效率。**注意**：上下文中片段2和5（API URL规范）与Python命名无关，已排除。\n\n### 依据的文档标题\n企业内部Python开发编码规范（检索到的片段1、3、4、6）','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}]','2026-05-11 16:53:12'),
(45,31,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 07:51:37'),
(46,31,'ASSISTANT','## Python 命名规范\n\n根据检索到的上下文（**片段 1**），公司内部 Python 项目遵循的命名规范如下。内容严格依据《Python开发编码规范》中“二、命名规范”部分定义：\n\n### 2.1 模块和包命名\n- 模块名使用小写字母，多个单词之间用下划线连接（例如：`user_service.py`）\n- 包名使用小写字母，尽量不使用下划线（例如：`utils`、`models`）\n\n### 2.2 类命名\n- 使用大驼峰命名法（PascalCase）（例如：`UserService`、`OrderManager`）\n- 异常类以 `Error` 或 `Exception` 结尾（例如：`InvalidTokenError`）\n\n### 2.3 函数和方法命名\n- 使用小写字母和下划线（例如：`get_user_info`、`calculate_total_price`）\n- 私有方法以单下划线开头（例如：`_validate_input`）\n- 布尔类型的方法或变量建议使用 `is_`、`has_`、`can_` 前缀\n\n### 2.4 变量命名\n- 使用小写字母和下划线（例如：`user_name`、`order_count`）\n- 常量使用全大写字母和下划线（例如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`）\n- 避免使用单字母变量名（循环变量 `i`、`j`、`k` 除外）\n\n### 2.5 数据库相关命名\n- 数据库名以 `db_` 开头\n- 表名以 `t_` 开头，使用小写和下划线\n- 字段名使用小写和下划线\n\n依据的文档标题：`Python开发编码规范` (片段 1)','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}]','2026-05-12 07:51:37'),
(47,32,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 07:52:26'),
(48,32,'ASSISTANT','# 知识库响应\n\n知识库检索未命中足够相关的片段，因此**知识库中未找到相关信息**。  \n\n作为「Java1234 RAG 企业知识库」的智能助手，我严格遵循系统说明：**不编造任何内容**，仅基于检索结果作答。  \n\n依据的文档标题：无','[]','2026-05-12 07:52:26'),
(49,34,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 08:00:41'),
(50,34,'ASSISTANT','# 知识库中未找到相关信息\n\n知识库检索未命中足够相关的片段，因此无法提供Python命名规范的信息。请确保在知识库中添加相关文档（如PEP 8规范等）以获取准确答案。\n\n依据的文档标题：无','[]','2026-05-12 08:00:41'),
(51,35,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 08:07:59'),
(52,35,'ASSISTANT','# 知识库响应\n\n知识库中未找到相关信息。\n\n依据的文档标题：无','[]','2026-05-12 08:07:59'),
(53,36,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 08:11:16'),
(54,36,'ASSISTANT','# 知识库检索结果\n\n知识库中未找到相关信息。\n\n依据的文档标题：无','[]','2026-05-12 08:11:16'),
(55,37,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 08:17:23'),
(56,37,'ASSISTANT','## 答案\n\n知识库中未找到相关信息。\n\n依据的文档标题：无','[]','2026-05-12 08:17:23'),
(57,38,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 08:20:21'),
(58,38,'ASSISTANT','# Python 命名规范\n\n根据知识库中检索到的片段（严格基于片段1内容），以下是公司内部Python项目的命名规范要求。规范内容直接来源于**Python开发编码规范**（片段1），未与其他片段冲突。\n\n## 1. 模块和包命名\n- 模块名使用小写字母，多个单词之间用下划线连接，例如：`user_service.py`\n- 包名使用小写字母，尽量不使用下划线，例如：`utils`、`models`\n\n## 2. 类命名\n- 使用大驼峰命名法（PascalCase），例如：`UserService`、`OrderManager`\n- 异常类以 `Error` 或 `Exception` 结尾，例如：`InvalidTokenError`\n\n## 3. 函数和方法命名\n- 使用小写字母和下划线，例如：`get_user_info`、`calculate_total_price`\n- 私有方法以单下划线开头，例如：`_validate_input`\n- 布尔类型的方法或变量建议使用 `is_`、`has_`、`can_` 前缀\n\n## 4. 变量命名\n- 使用小写字母和下划线，例如：`user_name`、`order_count`\n- 常量使用全大写字母和下划线，例如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`\n- 避免使用单字母变量名（循环变量 `i`、`j`、`k` 除外）\n\n## 5. 数据库相关命名\n- 数据库名以 `db_` 开头\n- 表名以 `t_` 开头，使用小写和下划线\n- 字段名使用小写和下划线\n\n---\n\n**依据的文档标题**：  \n知识库片段：`Python开发编码规范`（片段1）','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}]','2026-05-12 08:20:21'),
(59,45,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 09:23:06'),
(60,45,'ASSISTANT','## Python 命名规范\n\n根据检索到的上下文，公司内部Python项目的命名规范主要包含以下内容（严格依据片段1的“二、命名规范”部分）：\n\n1. **模块和包命名**\n   - 模块名使用小写字母，多个单词之间用下划线连接，如：`user_service.py`\n   - 包名使用小写字母，尽量不使用下划线，如：`utils`、`models`\n\n2. **类命名**\n   - 使用大驼峰命名法（PascalCase），如：`UserService`、`OrderManager`\n   - 异常类以 `Error` 或 `Exception` 结尾，如：`InvalidTokenError`\n\n3. **函数和方法命名**\n   - 使用小写字母和下划线，如：`get_user_info`、`calculate_total_price`\n   - 私有方法以单下划线开头，如：`_validate_input`\n   - 布尔类型的方法或变量建议使用 `is_`、`has_`、`can_` 前缀\n\n4. **变量命名**\n   - 使用小写字母和下划线，如：`user_name`、`order_count`\n   - 常量使用全大写字母和下划线，如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`\n   - 避免使用单字母变量名（循环变量 `i`、`j`、`k` 除外）\n\n5. **数据库相关命名**\n   - 数据库名以 `db_` 开头\n   - 表名以 `t_` 开头，使用小写和下划线\n   - 字段名使用小写和下划线\n\n> **说明**：以上内容完全基于检索到的片段1（无标题）中“Python开发编码规范”的命名规范部分，未涉及其他片段（片段2中无命名规范相关内容）。\n\n依据的文档标题：`Python开发编码规范`（片段1）','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}]','2026-05-12 09:23:06'),
(61,46,'USER','python 命名规范 有哪些 ？',NULL,'2026-05-12 09:42:06'),
(62,46,'ASSISTANT','# Python 命名规范\n\n根据检索到的上下文（片段1：**Python开发编码规范**），公司内部Python项目的命名规范具体如下：\n\n## 模块和包命名\n- 模块名使用小写字母，多个单词之间用下划线连接，例如：`user_service.py`\n- 包名使用小写字母，尽量不使用下划线，例如：`utils`、`models`\n\n## 类命名\n- 使用大驼峰命名法（PascalCase），例如：`UserService`、`OrderManager`\n- 异常类以 `Error` 或 `Exception` 结尾，例如：`InvalidTokenError`\n\n## 函数和方法命名\n- 使用小写字母和下划线，例如：`get_user_info`、`calculate_total_price`\n- 私有方法以单下划线开头，例如：`_validate_input`\n- 布尔类型的方法或变量建议使用 `is_`、`has_`、`can_` 前缀\n\n## 变量命名\n- 使用小写字母和下划线，例如：`user_name`、`order_count`\n- 常量使用全大写字母和下划线，例如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`\n- 避免使用单字母变量名（循环变量 `i`、`j`、`k` 除外）\n\n## 数据库相关命名\n- 数据库名以 `db_` 开头\n- 表名以 `t_` 开头，使用小写和下划线\n- 字段名使用小写和下划线\n\n> **依据说明**：本回答严格基于检索到的片段1（**Python开发编码规范**）内容，未引入其他信息。片段2（异常处理、日志规范等）不涉及命名规范，故未纳入。','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}]','2026-05-12 09:42:06'),
(63,47,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 09:52:00'),
(64,47,'ASSISTANT','# 企业OA密码要求\n\n根据检索到的上下文，企业OA系统密码要求如下：\n\n- 密码长度不少于8位\n- 须包含大小写字母、数字和特殊字符中的至少三种\n- 密码有效期为90天，到期后系统将提示修改\n- 连续5次输入错误密码，账号将被锁定30分钟\n\n**依据的文档标题**：企业OA系统使用手册（片段9）','[{\"docId\": null, \"title\": null, \"snippet\": \"分页：?page=1&page_size=20 排序：?sort=create_time&order=desc 筛选：?status=active&role=admin 搜索：?keyword=张三\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"企业OA系统使用手册\\n\\n一、系统概述\\n\\n企业OA办公自动化系统是公司内部日常办公管理的核心平台，涵盖流程审批、通知公告、日程管理、通讯录、文档中心等功能模块。本手册将详细介绍各功能模块的使用方法，帮助员工快速上手使用。\\n\\n系统访问地址：http://oa.company.com\\n技术支持邮箱：it-support@company.com\\n技术支持电话：内线8888\\n\\n二、登录与账号管理\\n\\n2.1 首次登录\\n- 新员工入职后，IT部门将在1个工作日内开通OA账号\\n- 初始用户名…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}]','2026-05-12 09:52:00'),
(65,48,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 09:55:31'),
(66,48,'ASSISTANT','# 企业OA密码要求\n\n根据检索到的知识片段，企业OA系统的密码要求如下（直接引用自《企业OA系统使用手册》）：\n\n- 密码长度不少于8位  \n- 须包含大小写字母、数字和特殊字符中的至少三种  \n- 密码有效期为90天，到期后系统将提示修改  \n- 连续5次输入错误密码，账号将被锁定30分钟  \n\n> **说明**：以上要求均源自企业OA系统使用手册的“登录与账号管理”部分（2.2 密码要求），是唯一明确描述密码规则的上下文片段。\n\n依据的文档标题：企业OA系统使用手册','[{\"docId\": null, \"title\": null, \"snippet\": \"分页：?page=1&page_size=20 排序：?sort=create_time&order=desc 筛选：?status=active&role=admin 搜索：?keyword=张三\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"企业OA系统使用手册\\n\\n一、系统概述\\n\\n企业OA办公自动化系统是公司内部日常办公管理的核心平台，涵盖流程审批、通知公告、日程管理、通讯录、文档中心等功能模块。本手册将详细介绍各功能模块的使用方法，帮助员工快速上手使用。\\n\\n系统访问地址：http://oa.company.com\\n技术支持邮箱：it-support@company.com\\n技术支持电话：内线8888\\n\\n二、登录与账号管理\\n\\n2.1 首次登录\\n- 新员工入职后，IT部门将在1个工作日内开通OA账号\\n- 初始用户名…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}]','2026-05-12 09:55:31'),
(67,49,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 09:57:47'),
(68,49,'ASSISTANT','## 企业OA密码要求\n\n根据检索到的上下文，企业OA系统的密码要求具体如下（来源于企业OA系统使用手册）：\n\n- 密码长度不少于8位  \n- 须包含大小写字母、数字和特殊字符中的至少三种  \n- 密码有效期为90天，到期后系统将提示修改  \n- 连续5次输入错误密码，账号将被锁定30分钟  \n\n> **说明**：以上要求严格依据企业OA系统使用手册中“二、登录与账号管理”部分的2.2节内容提取，未与其他片段冲突。\n\n依据的文档标题：企业OA系统使用手册','[{\"docId\": null, \"title\": null, \"snippet\": \"分页：?page=1&page_size=20 排序：?sort=create_time&order=desc 筛选：?status=active&role=admin 搜索：?keyword=张三\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"企业OA系统使用手册\\n\\n一、系统概述\\n\\n企业OA办公自动化系统是公司内部日常办公管理的核心平台，涵盖流程审批、通知公告、日程管理、通讯录、文档中心等功能模块。本手册将详细介绍各功能模块的使用方法，帮助员工快速上手使用。\\n\\n系统访问地址：http://oa.company.com\\n技术支持邮箱：it-support@company.com\\n技术支持电话：内线8888\\n\\n二、登录与账号管理\\n\\n2.1 首次登录\\n- 新员工入职后，IT部门将在1个工作日内开通OA账号\\n- 初始用户名…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}]','2026-05-12 09:57:47'),
(69,51,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 10:03:07'),
(70,51,'ASSISTANT','# 企业OA密码要求\n\n知识库中未找到相关信息。\n\n依据：知识库检索未命中足够相关的片段。','[]','2026-05-12 10:03:07'),
(71,52,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 10:04:32'),
(72,52,'ASSISTANT','## 企业OA密码要求查询结果\n\n知识库中未找到相关信息。\n\n依据的文档标题：无','[]','2026-05-12 10:04:32'),
(73,53,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 10:07:48'),
(74,53,'ASSISTANT','# 知识库信息\n\n知识库检索未命中足够相关的片段，因此无法提供企业OA密码要求的具体信息。根据系统说明，**知识库中未找到相关信息**，请勿编造内容。\n\n依据的文档标题：无','[]','2026-05-12 10:07:48'),
(75,55,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 10:17:16'),
(76,55,'ASSISTANT','## 企业OA密码要求\n\n根据检索到的知识片段，企业OA系统的密码要求如下：\n\n- **密码长度**：不少于8位  \n- **字符组成**：须包含大小写字母、数字和特殊字符中的至少三种  \n- **密码有效期**：90天，到期后系统将提示修改  \n- **安全机制**：连续5次输入错误密码，账号将被锁定30分钟  \n\n> **说明**：以上要求均直接来源于企业OA系统使用手册中“登录与账号管理”部分的密码规则描述。\n\n依据的文档标题：企业OA系统使用手册','[{\"docId\": null, \"title\": null, \"snippet\": \"分页：?page=1&page_size=20 排序：?sort=create_time&order=desc 筛选：?status=active&role=admin 搜索：?keyword=张三\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"企业OA系统使用手册\\n\\n一、系统概述\\n\\n企业OA办公自动化系统是公司内部日常办公管理的核心平台，涵盖流程审批、通知公告、日程管理、通讯录、文档中心等功能模块。本手册将详细介绍各功能模块的使用方法，帮助员工快速上手使用。\\n\\n系统访问地址：http://oa.company.com\\n技术支持邮箱：it-support@company.com\\n技术支持电话：内线8888\\n\\n二、登录与账号管理\\n\\n2.1 首次登录\\n- 新员工入职后，IT部门将在1个工作日内开通OA账号\\n- 初始用户名…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}]','2026-05-12 10:17:16'),
(77,56,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 10:18:57'),
(78,56,'ASSISTANT','# 知识库未命中相关信息\n\n知识库检索未命中足够相关的片段，因此无法提供企业OA密码要求的相关信息。根据系统说明，我不能编造任何内容。\n\n**依据的文档标题**：无','[]','2026-05-12 10:18:57'),
(79,57,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 10:22:14'),
(80,57,'ASSISTANT','**企业OA密码要求**\n\n根据检索到的知识片段，企业OA系统的密码要求具体如下（依据《企业OA系统使用手册》第2.2节）：\n\n- 密码长度不少于8位  \n- 须包含大小写字母、数字和特殊字符中的至少三种  \n- 密码有效期为90天，到期后系统将提示修改  \n- 连续5次输入错误密码，账号将被锁定30分钟  \n\n依据的文档：企业OA系统使用手册','[{\"docId\": null, \"title\": null, \"snippet\": \"分页：?page=1&page_size=20 排序：?sort=create_time&order=desc 筛选：?status=active&role=admin 搜索：?keyword=张三\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"企业OA系统使用手册\\n\\n一、系统概述\\n\\n企业OA办公自动化系统是公司内部日常办公管理的核心平台，涵盖流程审批、通知公告、日程管理、通讯录、文档中心等功能模块。本手册将详细介绍各功能模块的使用方法，帮助员工快速上手使用。\\n\\n系统访问地址：http://oa.company.com\\n技术支持邮箱：it-support@company.com\\n技术支持电话：内线8888\\n\\n二、登录与账号管理\\n\\n2.1 首次登录\\n- 新员工入职后，IT部门将在1个工作日内开通OA账号\\n- 初始用户名…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}]','2026-05-12 10:22:14'),
(81,58,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 10:24:13'),
(82,58,'ASSISTANT','## 企业OA密码要求\n\n根据检索到的上下文，企业OA系统的密码要求如下（直接来源于**企业OA系统使用手册**）：\n\n- 密码长度不少于8位  \n- 须包含大小写字母、数字和特殊字符中的至少三种  \n- 密码有效期为90天，到期后系统将提示修改  \n- 连续5次输入错误密码，账号将被锁定30分钟  \n\n### 依据的文档标题\n企业OA系统使用手册（片段9）','[{\"docId\": null, \"title\": null, \"snippet\": \"分页：?page=1&page_size=20 排序：?sort=create_time&order=desc 筛选：?status=active&role=admin 搜索：?keyword=张三\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"企业OA系统使用手册\\n\\n一、系统概述\\n\\n企业OA办公自动化系统是公司内部日常办公管理的核心平台，涵盖流程审批、通知公告、日程管理、通讯录、文档中心等功能模块。本手册将详细介绍各功能模块的使用方法，帮助员工快速上手使用。\\n\\n系统访问地址：http://oa.company.com\\n技术支持邮箱：it-support@company.com\\n技术支持电话：内线8888\\n\\n二、登录与账号管理\\n\\n2.1 首次登录\\n- 新员工入职后，IT部门将在1个工作日内开通OA账号\\n- 初始用户名…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}]','2026-05-12 10:24:13'),
(83,59,'USER','企业OK 密码要求有哪些？',NULL,'2026-05-12 10:37:10'),
(84,59,'ASSISTANT','# 知识库中未找到相关信息\n\n根据检索到的所有知识片段（片段 1 至片段 10），**未发现与“企业OK 密码要求”直接相关的内容**。  \n\n### 原因分析\n- **用户问题中的“企业OK”表述不明确**：在企业系统上下文中，“企业OK”并非标准术语，可能为打字错误或简写（例如，用户可能意指“企业密码要求”）。但所有检索片段均未提及“OK”相关概念。\n- **知识库中无密码要求的具体内容**：  \n  - 片段 1、3、4、5、6 等片段涉及认证、请求头、安全校验等，但**未指定密码的强度规则、长度要求、复杂度等密码策略**（例如，密码长度、字符类型、有效期等）。  \n  - 片段 4 提及“敏感数据传输必须加密”和“输入参数校验”，但这是通用安全措施，**不等同于密码要求**。  \n  - 片段 7-8、9、10 与密码要求无关（涉及请假流程、文档编辑、应用下载等）。  \n- **关键冲突点**：用户问题中“密码要求”在知识库中无直接对应表述（片段 2 仅包含错误响应示例，无密码规则）。\n\n### 依据的文档标题\n所有检索到的片段均无标题（均标注“无标题”），且**无任何片段包含企业密码要求的具体规则**。因此，知识库中未找到相关信息。\n\n> **提示**：建议用户确认问题表述（例如，是否指“企业密码策略”或“API 密码认证规则”），或提供更明确的上下文。当前检索结果不足以回答此问题。','[{\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"为规范公司员工请假管理流程，保障员工合法休假权益，确保公司各项工作正常运转，特制定本办法。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"iOS：在App Store搜索\\\"公司项目管理\\\"下载 Android：在应用宝或公司内部应用市场下载\", \"categoryId\": null}]','2026-05-12 10:37:10'),
(85,59,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 10:39:37'),
(86,59,'ASSISTANT','# 企业OA密码要求\n\n根据知识库检索结果，企业OA系统密码要求如下：\n\n- 密码长度不少于8位\n- 须包含大小写字母、数字和特殊字符中的至少三种\n- 密码有效期为90天，到期后系统将提示修改\n- 连续5次输入错误密码，账号将被锁定30分钟\n\n**依据的文档标题**：企业OA系统使用手册（片段9）','[{\"docId\": null, \"title\": null, \"snippet\": \"分页：?page=1&page_size=20 排序：?sort=create_time&order=desc 筛选：?status=active&role=admin 搜索：?keyword=张三\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"企业OA系统使用手册\\n\\n一、系统概述\\n\\n企业OA办公自动化系统是公司内部日常办公管理的核心平台，涵盖流程审批、通知公告、日程管理、通讯录、文档中心等功能模块。本手册将详细介绍各功能模块的使用方法，帮助员工快速上手使用。\\n\\n系统访问地址：http://oa.company.com\\n技术支持邮箱：it-support@company.com\\n技术支持电话：内线8888\\n\\n二、登录与账号管理\\n\\n2.1 首次登录\\n- 新员工入职后，IT部门将在1个工作日内开通OA账号\\n- 初始用户名…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}]','2026-05-12 10:39:37'),
(87,60,'USER','python 命名规范 有哪些？',NULL,'2026-05-12 10:47:57'),
(88,60,'ASSISTANT','# Python 命名规范\n\n根据公司内部检索到的上下文（片段1），Python 命名规范具体包括以下内容：\n\n- **模块和包命名**\n  - 模块名使用小写字母，多个单词之间用下划线连接，例如：`user_service.py`\n  - 包名使用小写字母，尽量不使用下划线，例如：`utils`、`models`\n\n- **类命名**\n  - 使用大驼峰命名法（PascalCase），例如：`UserService`、`OrderManager`\n  - 异常类以 `Error` 或 `Exception` 结尾，例如：`InvalidTokenError`\n\n- **函数和方法命名**\n  - 使用小写字母和下划线，例如：`get_user_info`、`calculate_total_price`\n  - 私有方法以单下划线开头，例如：`_validate_input`\n  - 布尔类型的方法或变量建议使用 `is_`、`has_`、`can_` 前缀\n\n- **变量命名**\n  - 使用小写字母和下划线，例如：`user_name`、`order_count`\n  - 常量使用全大写字母和下划线，例如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`\n  - 避免使用单字母变量名（循环变量 `i`、`j`、`k` 除外）\n\n- **数据库相关命名**\n  - 数据库名以 `db_` 开头\n  - 表名以 `t_` 开头，使用小写和下划线\n  - 字段名使用小写和下划线\n\n**依据的文档标题**：Python开发编码规范','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"POST和PUT请求使用JSON格式：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"文件上传使用multipart/form-data格式，文件字段名统一使用file。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"2 事务规范\\n\\n事务要尽可能短小。\\n\\n事务中避免进行外部服务调用。\\n\\n必须处理事务的异常回滚。\\n\\n六、安全规范\\n\\n数据库账号权限遵循最小权限原则。\\n\\n生产环境禁止使用root账号连接。\\n\\n敏感数据（如密码）必须加密存储。\\n\\n定期进行数据库备份，备份文件加密保存。\", \"categoryId\": null}]','2026-05-12 10:47:57'),
(89,61,'USER','python 命名规范 有哪些？',NULL,'2026-05-12 12:11:05'),
(90,61,'ASSISTANT','## Python 命名规范\n\n根据检索到的上下文，公司内部Python项目的命名规范如下（严格基于片段1的“二、命名规范”部分）：\n\n### 2.1 模块和包命名\n- 模块名使用小写字母，多个单词之间用下划线连接，例如：`user_service.py`\n- 包名使用小写字母，尽量不使用下划线，例如：`utils`、`models`\n\n### 2.2 类命名\n- 使用大驼峰命名法（PascalCase），例如：`UserService`、`OrderManager`\n- 异常类以 `Error` 或 `Exception` 结尾，例如：`InvalidTokenError`\n\n### 2.3 函数和方法命名\n- 使用小写字母和下划线，例如：`get_user_info`、`calculate_total_price`\n- 私有方法以单下划线开头，例如：`_validate_input`\n- 布尔类型的方法或变量建议使用 `is_`、`has_`、`can_` 前缀\n\n### 2.4 变量命名\n- 使用小写字母和下划线，例如：`user_name`、`order_count`\n- 常量使用全大写字母和下划线，例如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`\n- 避免使用单字母变量名（循环变量 `i`、`j`、`k` 除外）\n\n### 2.5 数据库相关命名\n- 数据库名以 `db_` 开头\n- 表名以 `t_` 开头，使用小写和下划线\n- 字段名使用小写和下划线\n\n依据的文档标题：片段 1 · (无标题)','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"POST和PUT请求使用JSON格式：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"文件上传使用multipart/form-data格式，文件字段名统一使用file。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"2 事务规范\\n\\n事务要尽可能短小。\\n\\n事务中避免进行外部服务调用。\\n\\n必须处理事务的异常回滚。\\n\\n六、安全规范\\n\\n数据库账号权限遵循最小权限原则。\\n\\n生产环境禁止使用root账号连接。\\n\\n敏感数据（如密码）必须加密存储。\\n\\n定期进行数据库备份，备份文件加密保存。\", \"categoryId\": null}]','2026-05-12 12:11:05'),
(91,62,'USER','企业OA 密码要求有哪些？',NULL,'2026-05-12 12:14:09'),
(92,62,'ASSISTANT','# 企业OA密码要求\n\n根据检索到的知识片段，企业OA系统密码要求如下：\n\n- **密码长度不少于8位**\n- **须包含大小写字母、数字和特殊字符中的至少三种**\n- **密码有效期为90天，到期后系统将提示修改**\n- **连续5次输入错误密码，账号将被锁定30分钟**\n\n---\n\n依据的文档标题：**企业OA系统使用手册**（片段 9）','[{\"docId\": null, \"title\": null, \"snippet\": \"分页：?page=1&page_size=20 排序：?sort=create_time&order=desc 筛选：?status=active&role=admin 搜索：?keyword=张三\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"必须包含以下请求头： Content-Type: application/json（POST/PUT请求） Authorization: Bearer {token}（需认证的接口） Accept-Language: zh-CN（可选，指定语言）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"采用JWT（JSON Web Token）进行身份认证 Token通过登录接口获取，有效期为24小时 请求需在Header中携带Authorization: Bearer {token}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"登录接口：同一IP每分钟最多10次 普通接口：同一用户每分钟最多60次 上传接口：同一用户每分钟最多5次\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有API请求须记录访问日志 日志包含：请求时间、用户ID、请求URL、请求方法、响应状态码、响应时间 敏感信息（密码等）不得记录在日志中\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"员工请假须通过OA系统提交请假申请 申请内容包括：假期类型、起止时间、请假原因、工作交接安排 需要附件材料的须一并上传（如病假条、结婚证等）\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"企业OA系统使用手册\\n\\n一、系统概述\\n\\n企业OA办公自动化系统是公司内部日常办公管理的核心平台，涵盖流程审批、通知公告、日程管理、通讯录、文档中心等功能模块。本手册将详细介绍各功能模块的使用方法，帮助员工快速上手使用。\\n\\n系统访问地址：http://oa.company.com\\n技术支持邮箱：it-support@company.com\\n技术支持电话：内线8888\\n\\n二、登录与账号管理\\n\\n2.1 首次登录\\n- 新员工入职后，IT部门将在1个工作日内开通OA账号\\n- 初始用户名…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"支持多人同时在线编辑文档 自动保存，支持版本回溯 支持Markdown和富文本两种编辑模式\", \"categoryId\": null}]','2026-05-12 12:14:09'),
(93,63,'USER','python 命名规范 有哪些？',NULL,'2026-05-12 12:20:25'),
(94,63,'ASSISTANT','## Python 命名规范\n\n根据检索到的知识片段，以下为公司内部Python项目的命名规范（严格依据片段 1 的内容）。该规范主要参考PEP 8，并结合公司项目实际情况进行调整。\n\n### 2.1 模块和包命名\n- 模块名使用小写字母，多个单词之间用下划线连接，例如：`user_service.py`。\n- 包名使用小写字母，尽量不使用下划线，例如：`utils`、`models`。\n\n### 2.2 类命名\n- 使用大驼峰命名法（PascalCase），例如：`UserService`、`OrderManager`。\n- 异常类以 `Error` 或 `Exception` 结尾，例如：`InvalidTokenError`。\n\n### 2.3 函数和方法命名\n- 使用小写字母和下划线，例如：`get_user_info`、`calculate_total_price`。\n- 私有方法以单下划线开头，例如：`_validate_input`。\n- 布尔类型的方法或变量建议使用 `is_`、`has_`、`can_` 前缀。\n\n### 2.4 变量命名\n- 使用小写字母和下划线，例如：`user_name`、`order_count`。\n- 常量使用全大写字母和下划线，例如：`MAX_RETRY_COUNT`、`DEFAULT_TIMEOUT`。\n- 避免使用单字母变量名（循环变量 `i`、`j`、`k` 除外）。\n\n### 2.5 数据库相关命名\n- 数据库名以 `db_` 开头。\n- 表名以 `t_` 开头，使用小写和下划线。\n- 字段名使用小写和下划线。\n\n---\n\n**依据的文档标题**：  \n`Python开发编码规范`（片段 1）','[{\"docId\": null, \"title\": null, \"snippet\": \"Python开发编码规范\\n\\n一、概述\\n\\n本规范旨在统一公司内部Python项目的编码风格，提高代码可读性和可维护性。所有Python项目开发人员须遵循本规范进行代码编写。本规范主要参考PEP 8编码规范，并结合公司项目实际情况进行了补充和调整。\\n\\n二、命名规范\\n\\n2.1 模块和包命名\\n- 模块名使用小写字母，多个单词之间用下划线连接，如：user_service.py\\n- 包名使用小写字母，尽量不使用下划线，如：utils、models\\n\\n2.2 类命名\\n- 使用大驼峰命名法…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"- 不要使用裸露的except语句，应指定具体的异常类型\\n- 异常处理中应记录日志\\n- 对外部服务调用必须进行异常捕获\\n\\n5.2 异常抛出\\n- 自定义异常应继承自Exception或其子类\\n- 异常信息应清晰描述错误原因\\n\\n六、日志规范\\n\\n6.1 日志级别\\n- DEBUG：调试信息，仅在开发环境使用\\n- INFO：正常业务流程的关键节点信息\\n- WARNING：潜在问题的警告信息\\n- ERROR：错误信息，但程序可继续运行\\n- CRITICAL：严重错误，程序可能无法继续运行…\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"本规范旨在统一公司内部所有RESTful API的设计标准，确保接口的一致性、可读性和可维护性。所有后端开发人员在设计和开发API时须遵循本规范。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"使用HTTPS协议 API版本号放在URL中，如：/api/v1/users 使用名词复数形式表示资源，如：/users、/orders URL中使用小写字母和连字符，如：/user-profiles URL层级不超过3层\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"POST和PUT请求使用JSON格式：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"文件上传使用multipart/form-data格式，文件字段名统一使用file。\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有接口返回统一的JSON结构：\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"{\\n  \\\"code\\\": 400,\\n  \\\"message\\\": \\\"用户名不能为空\\\",\\n  \\\"data\\\": null\\n}\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"所有输入参数必须进行类型和长度校验 防止SQL注入、XSS攻击 敏感数据传输必须加密\", \"categoryId\": null}, {\"docId\": null, \"title\": null, \"snippet\": \"2 事务规范\\n\\n事务要尽可能短小。\\n\\n事务中避免进行外部服务调用。\\n\\n必须处理事务的异常回滚。\\n\\n六、安全规范\\n\\n数据库账号权限遵循最小权限原则。\\n\\n生产环境禁止使用root账号连接。\\n\\n敏感数据（如密码）必须加密存储。\\n\\n定期进行数据库备份，备份文件加密保存。\", \"categoryId\": null}]','2026-05-12 12:20:25');

/*Table structure for table `t_chat_session` */

DROP TABLE IF EXISTS `t_chat_session`;

CREATE TABLE `t_chat_session` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '会话标题',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='聊天会话';

/*Data for the table `t_chat_session` */

insert  into `t_chat_session`(`id`,`user_id`,`title`,`create_time`,`update_time`) values 
(2,1,'项目开发 统一响应结构 如何设计？','2026-05-11 15:05:40','2026-05-11 15:11:16'),
(3,1,'项目开发 统一响应结构 如何设计？','2026-05-11 15:08:14','2026-05-11 15:16:24'),
(4,1,'项目 统一响应结构 规范是啥？','2026-05-11 15:10:48','2026-05-11 15:16:24'),
(6,1,'项目 统一响应结构 规范是啥？','2026-05-11 15:16:31','2026-05-11 15:22:33'),
(7,1,'项目 统一响应结构 规范是啥？','2026-05-11 15:23:28','2026-05-11 15:26:15'),
(8,1,'公司密码要求是啥？','2026-05-11 15:27:28','2026-05-11 15:28:31'),
(9,1,'企业OA系统账号密码要求有哪些？','2026-05-11 15:29:38','2026-05-11 15:30:28'),
(10,1,'新员工入职手续有哪些？','2026-05-11 15:31:33','2026-05-11 15:32:45'),
(11,1,'新员工入职手续有哪些？','2026-05-11 15:32:58','2026-05-11 15:34:14'),
(12,1,'python命名规范有哪些?','2026-05-11 15:35:15','2026-05-11 15:38:47'),
(13,1,'python命名规范有哪些?','2026-05-11 15:39:02','2026-05-11 15:40:03'),
(14,1,'python命名规范有哪些?','2026-05-11 15:44:00','2026-05-11 15:45:05'),
(15,1,'python命名规范有哪些?','2026-05-11 15:45:17','2026-05-11 15:49:15'),
(16,1,'python命名规范有哪些?','2026-05-11 15:55:13','2026-05-11 15:56:17'),
(18,1,'Python 命名规范有哪些？','2026-05-11 15:59:57','2026-05-11 16:01:03'),
(19,1,'python命名规范有哪些？','2026-05-11 16:15:07','2026-05-11 16:16:18'),
(20,1,'python命名规范有哪些？','2026-05-11 16:22:59','2026-05-11 16:24:07'),
(25,1,'python命名规范有哪些？','2026-05-11 16:29:14','2026-05-11 16:30:19'),
(26,1,'python命名规范有哪些？','2026-05-11 16:47:24','2026-05-11 16:48:36'),
(27,1,'python命名规范有哪些？','2026-05-11 16:48:44','2026-05-11 16:53:12'),
(31,1,'python 命名规范 有哪些 ？','2026-05-12 07:49:37','2026-05-12 07:51:37'),
(32,1,'python 命名规范 有哪些 ？','2026-05-12 07:51:43','2026-05-12 07:52:26'),
(34,1,'python 命名规范 有哪些 ？','2026-05-12 07:59:28','2026-05-12 08:00:41'),
(35,1,'python 命名规范 有哪些 ？','2026-05-12 08:07:19','2026-05-12 08:07:59'),
(36,1,'python 命名规范 有哪些 ？','2026-05-12 08:08:45','2026-05-12 08:11:16'),
(37,1,'python 命名规范 有哪些 ？','2026-05-12 08:15:21','2026-05-12 08:17:23'),
(38,1,'python 命名规范 有哪些 ？','2026-05-12 08:17:58','2026-05-12 08:20:21'),
(45,1,'python 命名规范 有哪些 ？','2026-05-12 09:19:24','2026-05-12 09:23:06'),
(46,1,'python 命名规范 有哪些 ？','2026-05-12 09:39:00','2026-05-12 09:42:06'),
(47,1,'企业OA 密码要求有哪些？','2026-05-12 09:50:26','2026-05-12 09:52:00'),
(48,1,'企业OA 密码要求有哪些？','2026-05-12 09:53:49','2026-05-12 09:55:31'),
(49,1,'企业OA 密码要求有哪些？','2026-05-12 09:56:01','2026-05-12 09:57:47'),
(51,1,'企业OA 密码要求有哪些？','2026-05-12 10:01:30','2026-05-12 10:03:07'),
(52,1,'企业OA 密码要求有哪些？','2026-05-12 10:03:25','2026-05-12 10:04:32'),
(53,1,'企业OA 密码要求有哪些？','2026-05-12 10:06:59','2026-05-12 10:07:48'),
(55,1,'企业OA 密码要求有哪些？','2026-05-12 10:15:30','2026-05-12 10:17:16'),
(56,1,'企业OA 密码要求有哪些？','2026-05-12 10:17:55','2026-05-12 10:18:57'),
(57,1,'企业OA 密码要求有哪些？','2026-05-12 10:20:21','2026-05-12 10:22:14'),
(58,1,'企业OA 密码要求有哪些？','2026-05-12 10:22:21','2026-05-12 10:24:13'),
(59,2,'企业OK 密码要求有哪些？','2026-05-12 10:34:45','2026-05-12 10:39:37'),
(60,2,'python 命名规范 有哪些？','2026-05-12 10:43:51','2026-05-12 10:47:57'),
(61,1,'python 命名规范 有哪些？','2026-05-12 12:07:53','2026-05-12 12:11:05'),
(62,2,'企业OA 密码要求有哪些？','2026-05-12 12:12:53','2026-05-12 12:14:09'),
(63,2,'python 命名规范 有哪些？','2026-05-12 12:18:10','2026-05-12 12:20:25');

/*Table structure for table `t_kb_category` */

DROP TABLE IF EXISTS `t_kb_category`;

CREATE TABLE `t_kb_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '分类名称',
  `description` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '描述',
  `icon` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '图标标识',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识库分类';

/*Data for the table `t_kb_category` */

insert  into `t_kb_category`(`id`,`name`,`description`,`icon`,`sort_order`,`create_time`) values 
(1,'技术文档','研发与接口说明类文档','Document',1,'2026-05-11 08:36:18'),
(2,'规章制度','公司制度与流程','Notebook',2,'2026-05-11 08:36:18'),
(3,'产品手册','产品使用说明','Goods',3,'2026-05-11 08:36:18');

/*Table structure for table `t_kb_document` */

DROP TABLE IF EXISTS `t_kb_document`;

CREATE TABLE `t_kb_document` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category_id` bigint NOT NULL COMMENT '分类ID',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '显示标题',
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始文件名',
  `file_path` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '磁盘相对路径（相对 uploads 根）',
  `file_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '扩展名小写',
  `file_size` bigint NOT NULL DEFAULT '0' COMMENT '字节大小',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PROCESSING' COMMENT 'PROCESSING/SUCCESS/FAIL',
  `vector_count` int NOT NULL DEFAULT '0' COMMENT '向量块数量',
  `upload_user_id` bigint DEFAULT NULL COMMENT '上传用户ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_category` (`category_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识文档';

/*Data for the table `t_kb_document` */

insert  into `t_kb_document`(`id`,`category_id`,`title`,`file_name`,`file_path`,`file_type`,`file_size`,`status`,`vector_count`,`upload_user_id`,`create_time`) values 
(22,1,'Python开发编码规范','Python开发编码规范.txt','202605/a8baaba43a4a4d3983ec60e239f336af.txt','txt',3208,'SUCCESS',2,1,'2026-05-12 07:48:24'),
(23,1,'API接口设计规范','API接口设计规范.md','202605/9c2aff2eee5f456ba0e9fda3c6147bd7.md','md',3709,'SUCCESS',20,1,'2026-05-12 09:45:36'),
(24,1,'Git版本管理规范','Git版本管理规范.docx','202605/fc2a47d7a4644a38a38cb89f078b9de8.docx','docx',38369,'SUCCESS',2,1,'2026-05-12 09:46:04'),
(25,1,'数据库设计规范','数据库设计规范.pdf','202605/dcaf33c6b43e4228b204a6b18af7ab74.pdf','pdf',44252,'SUCCESS',2,1,'2026-05-12 09:46:25'),
(26,2,'公司考勤管理制度','公司考勤管理制度.txt','202605/c6ff64663b494ca98a0ce1a3bd479e82.txt','txt',2930,'SUCCESS',2,1,'2026-05-12 09:46:51'),
(27,2,'公司薪酬福利制度','公司薪酬福利制度.pdf','202605/52dc94d6190c44bdb53a77ab25805181.pdf','pdf',46016,'SUCCESS',2,1,'2026-05-12 09:47:08'),
(28,2,'员工请假管理办法','员工请假管理办法.md','202605/4bfe2beca3fc46df9063e9342be6fa08.md','md',3304,'SUCCESS',13,1,'2026-05-12 09:47:27'),
(29,2,'员工行为规范手册','员工行为规范手册.docx','202605/7705d8001b454bf680f87b7dff254892.docx','docx',38464,'SUCCESS',2,1,'2026-05-12 09:47:49'),
(30,3,'企业OA系统使用手册','企业OA系统使用手册.txt','202605/802eba09da274dbbabb78454a258c4fa.txt','txt',3784,'SUCCESS',2,1,'2026-05-12 09:48:35'),
(31,3,'企业邮箱配置说明','企业邮箱配置说明.pdf','202605/20f8f125909e4109bf76bb62f58e4ba2.pdf','pdf',43360,'SUCCESS',1,1,'2026-05-12 09:49:10'),
(32,3,'项目管理平台操作指南','项目管理平台操作指南.md','202605/a173e71e97c641b0b2bf958d296b0537.md','md',4172,'SUCCESS',15,1,'2026-05-12 09:49:32'),
(33,3,'新员工入职指南','新员工入职指南.docx','202605/391552e0a97f47189bd5935902c71382.docx','docx',38585,'SUCCESS',2,1,'2026-05-12 09:49:55');

/*Table structure for table `t_system_log` */

DROP TABLE IF EXISTS `t_system_log`;

CREATE TABLE `t_system_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
  `action` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '动作描述',
  `ip` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'IP',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统日志';

/*Data for the table `t_system_log` */

insert  into `t_system_log`(`id`,`user_id`,`action`,`ip`,`create_time`) values 
(1,1,'登录系统','127.0.0.1','2026-05-05 08:36:18'),
(2,2,'提问','127.0.0.1','2026-05-06 08:36:18'),
(3,3,'提问','127.0.0.1','2026-05-07 08:36:18'),
(4,2,'提问','127.0.0.1','2026-05-08 08:36:18'),
(5,4,'登录系统','127.0.0.1','2026-05-09 08:36:18'),
(6,2,'提问','127.0.0.1','2026-05-10 08:36:18'),
(7,1,'登录系统','127.0.0.1','2026-05-11 08:46:32'),
(8,2,'登录系统','127.0.0.1','2026-05-11 13:43:12'),
(9,1,'登录系统','127.0.0.1','2026-05-11 13:57:23'),
(10,2,'登录系统','127.0.0.1','2026-05-11 15:14:59'),
(11,1,'登录系统','127.0.0.1','2026-05-11 15:16:19'),
(12,1,'登录系统','127.0.0.1','2026-05-11 16:14:52'),
(13,1,'登录系统','127.0.0.1','2026-05-12 07:30:22'),
(14,1,'登录系统','127.0.0.1','2026-05-12 10:32:49'),
(15,2,'登录系统','127.0.0.1','2026-05-12 10:33:00'),
(16,1,'登录系统','127.0.0.1','2026-05-12 12:07:25'),
(17,2,'登录系统','127.0.0.1','2026-05-12 12:12:09');

/*Table structure for table `t_user` */

DROP TABLE IF EXISTS `t_user`;

CREATE TABLE `t_user` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `username` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '登录名',
  `password` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'MD5 密码',
  `real_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '真实姓名',
  `avatar` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '头像相对路径',
  `role` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'USER' COMMENT '角色：ADMIN / USER',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：1正常 0禁用',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

/*Data for the table `t_user` */

insert  into `t_user`(`id`,`username`,`password`,`real_name`,`avatar`,`role`,`status`,`create_time`) values 
(1,'admin','e10adc3949ba59abbe56e057f20f883e','系统管理员','202605/251102e359374f6fb839628d14efca4d.png','ADMIN',1,'2026-05-11 08:36:18'),
(2,'user1','e10adc3949ba59abbe56e057f20f883e','张三','202605/68614ea1503b42f2bde58ed188015a10.png','USER',1,'2026-05-11 08:36:18'),
(3,'user2','e10adc3949ba59abbe56e057f20f883e','李四',NULL,'USER',1,'2026-05-11 08:36:18'),
(4,'user3','e10adc3949ba59abbe56e057f20f883e','王五',NULL,'USER',1,'2026-05-11 08:36:18');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
